import { BonusChallenge } from '../../src/types';
import { DailyChallengeStore, nullStore } from './store';

/** The seam for producing a bonus challenge. */
export interface BonusChallengeSource {
  next(letter: string): Promise<BonusChallenge>;
}

/** Tries the primary source and falls back on failure. */
export function withBonusFallback(
  primary: BonusChallengeSource,
  fallback: BonusChallengeSource
): BonusChallengeSource {
  return {
    async next(letter) {
      try {
        return await primary.next(letter);
      } catch (err) {
        console.error('Primary bonus source failed, falling back:', err);
        return fallback.next(letter);
      }
    },
  };
}

/**
 * Makes a source stable for a given day, across every replica.
 *
 * The daily puzzle's letter is derived deterministically from the date, but its
 * bonus challenge is generated by a model — so without coordination it changes
 * on every refresh and differs between players. Two layers stop that:
 *
 * - The **store** is the source of truth shared by all replicas. A replica that
 *   generates a challenge publishes it with putIfAbsent, so the first writer
 *   wins and everyone else adopts that value rather than overwriting it.
 * - The in-process **map** is a read-through cache, so the common path costs no
 *   network call. It caches the in-flight promise, which also collapses a
 *   first-request stampede within one replica.
 *
 * With the default nullStore this degrades to per-process caching, which is
 * correct for a single replica.
 */
export function cachedPerDate(
  sourceFor: (dateStr: string) => BonusChallengeSource,
  options: { store?: DailyChallengeStore; maxDays?: number } = {}
) {
  const store = options.store ?? nullStore;
  const maxDays = options.maxDays ?? 7;
  const cache = new Map<string, Promise<BonusChallenge>>();

  async function resolve(dateStr: string, letter: string): Promise<BonusChallenge> {
    const stored = await store.get(dateStr);
    if (stored) return stored;

    const generated = await sourceFor(dateStr).next(letter);

    // Another replica may have published one between the read and now; whichever
    // is stored wins, so every player sees the same challenge.
    return store.putIfAbsent(dateStr, generated);
  }

  return {
    async forDate(dateStr: string, letter: string): Promise<BonusChallenge> {
      const cached = cache.get(dateStr);
      if (cached) return cached;

      const pending = resolve(dateStr, letter);
      cache.set(dateStr, pending);

      // A failure must not be cached, or the day is poisoned until restart.
      pending.catch(() => cache.delete(dateStr));

      // Keep the map from growing without bound across a long-lived process.
      if (cache.size > maxDays) {
        const oldest = [...cache.keys()].sort()[0];
        if (oldest) cache.delete(oldest);
      }

      return pending;
    },
  };
}
