import { BonusChallenge } from './contract';

const FROZEN_CHALLENGES: BonusChallenge[] = [
  {
    id: 'long_words',
    title: 'Super Size Words',
    description: 'All 4 answers must be at least 5 letters long.',
    icon: 'Sparkles',
    ruleHint: 'Words must contain 5+ letters.',
    rule: { scope: 'all', checkKind: 'minLength', checkValue: '5' },
  },
  {
    id: 'india_focus',
    title: 'India Connection',
    description: 'At least 2 answers must have a connection to India or South Asia.',
    icon: 'Flag',
    ruleHint: 'Indian names, places, wildlife or cultural items.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'edible_thing',
    title: 'Foodie Delight',
    description: 'The "Thing" must be something edible or drinks/ingredients.',
    icon: 'Utensils',
    ruleHint: 'Thing must be food or drink.',
    rule: { scope: 'thing', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'world_place',
    title: 'Global Traveler',
    description: 'The "Place" must be a recognized country or capital city.',
    icon: 'Globe',
    ruleHint: 'Country or Capital City for Place.',
    rule: { scope: 'place', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'wildlife_expert',
    title: 'Wildlife Enthusiast',
    description: 'The "Animal" must be a wild animal (mammal, bird, or ocean creature).',
    icon: 'TreePine',
    ruleHint: 'Wild mammal, bird, or sea creature.',
    rule: { scope: 'animal', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'vowel_rich',
    title: 'Vowel Harmony',
    description: 'Every answer must contain at least 2 vowels (A, E, I, O, U).',
    icon: 'Layers',
    ruleHint: 'At least 2 vowels per word.',
    rule: { scope: 'all', checkKind: 'minVowels', checkValue: '2' },
  },
  {
    id: 'famous_name',
    title: 'Famous Persona',
    description: 'The "Name" must belong to a well-known historical or famous figure.',
    icon: 'Award',
    ruleHint: 'Famous/Historical person name.',
    rule: { scope: 'name', checkKind: 'none', checkValue: '' },
  },
];

const EXTRA_CHALLENGES: BonusChallenge[] = [
  {
    id: 'adjacent_vowels',
    title: 'Side By Side',
    description: 'Every answer must contain two vowels next to each other, like "ea" or "oo".',
    icon: 'Layers',
    ruleHint: 'Two vowels touching, e.g. "oo".',
    rule: { scope: 'all', checkKind: 'adjacentVowels', checkValue: '' },
  },
  {
    id: 'double_letter',
    title: 'Seeing Double',
    description: 'Every answer must contain the same letter twice in a row, like "ll" or "ss".',
    icon: 'Layers',
    ruleHint: 'A repeated letter pair in each word.',
    rule: { scope: 'all', checkKind: 'doubleLetter', checkValue: '' },
  },
  {
    id: 'ends_with_vowel',
    title: 'Soft Landing',
    description: 'Every answer must end with a vowel (A, E, I, O or U).',
    icon: 'Sparkles',
    ruleHint: 'Last letter must be a vowel.',
    rule: { scope: 'all', checkKind: 'endsWithVowel', checkValue: '' },
  },
  {
    id: 'very_long_words',
    title: 'The Long Haul',
    description: 'All 4 answers must be at least 7 letters long.',
    icon: 'Sparkles',
    ruleHint: 'Words must contain 7+ letters.',
    rule: { scope: 'all', checkKind: 'minLength', checkValue: '7' },
  },
  {
    id: 'long_thing',
    title: 'Big Thing Energy',
    description: 'The "Thing" must be at least 6 letters long.',
    icon: 'Layers',
    ruleHint: 'Thing needs 6+ letters.',
    rule: { scope: 'thing', checkKind: 'minLength', checkValue: '6' },
  },
  {
    id: 'flying_animal',
    title: 'Wings Required',
    description: 'The "Animal" must be one that can fly.',
    icon: 'TreePine',
    ruleHint: 'Animal must be able to fly.',
    rule: { scope: 'animal', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'natural_place',
    title: 'Force Of Nature',
    description: 'The "Place" must be a natural feature: a river, mountain, lake or desert.',
    icon: 'TreePine',
    ruleHint: 'River, mountain, lake or desert.',
    rule: { scope: 'place', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'wearable_thing',
    title: 'Dress Code',
    description: 'The "Thing" must be something you can wear.',
    icon: 'Sparkles',
    ruleHint: 'Thing must be wearable.',
    rule: { scope: 'thing', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'kitchen_thing',
    title: 'Kitchen Business',
    description: 'The "Thing" must be something you would find in a kitchen.',
    icon: 'Utensils',
    ruleHint: 'Thing belongs in a kitchen.',
    rule: { scope: 'thing', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'fictional_name',
    title: 'Straight From Fiction',
    description: 'The "Name" must be a character from a book, film or myth.',
    icon: 'Award',
    ruleHint: 'Fictional or mythological character.',
    rule: { scope: 'name', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'water_theme',
    title: 'Deep Water',
    description: 'At least 2 answers must be connected to the sea, rivers or lakes.',
    icon: 'Globe',
    ruleHint: 'Two answers linked to water.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'space_theme',
    title: 'Written In The Stars',
    description: 'At least 2 answers must be connected to space, stars or astronomy.',
    icon: 'Sparkles',
    ruleHint: 'Two answers linked to space.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'music_theme',
    title: 'In Good Rhythm',
    description: 'At least 2 answers must be connected to music or dance.',
    icon: 'Layers',
    ruleHint: 'Two answers linked to music.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'history_theme',
    title: 'Ancient Records',
    description: 'At least 2 answers must be connected to history or the ancient world.',
    icon: 'Award',
    ruleHint: 'Two answers linked to history.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'winter_theme',
    title: 'Chill Factor',
    description: 'At least 2 answers must be connected to ice, cold or winter.',
    icon: 'Globe',
    ruleHint: 'Two answers linked to the cold.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'medium_words',
    title: 'Middle Distance',
    description: 'All 4 answers must be at least 6 letters long.',
    icon: 'Sparkles',
    ruleHint: 'Words must contain 6+ letters.',
    rule: { scope: 'all', checkKind: 'minLength', checkValue: '6' },
  },
  {
    id: 'triple_vowels',
    title: 'Three Vowel Threat',
    description: 'Every answer must contain at least 3 vowels (A, E, I, O, U).',
    icon: 'Layers',
    ruleHint: 'At least 3 vowels per word.',
    rule: { scope: 'all', checkKind: 'minVowels', checkValue: '3' },
  },
  {
    id: 'long_name',
    title: 'A Name With Length',
    description: 'The "Name" must be at least 6 letters long.',
    icon: 'Award',
    ruleHint: 'Name needs 6+ letters.',
    rule: { scope: 'name', checkKind: 'minLength', checkValue: '6' },
  },
  {
    id: 'long_place',
    title: 'The Scenic Route',
    description: 'The "Place" must be at least 7 letters long.',
    icon: 'Globe',
    ruleHint: 'Place needs 7+ letters.',
    rule: { scope: 'place', checkKind: 'minLength', checkValue: '7' },
  },
  {
    id: 'long_animal',
    title: 'Big Beast Names',
    description: 'The "Animal" must be at least 7 letters long.',
    icon: 'TreePine',
    ruleHint: 'Animal needs 7+ letters.',
    rule: { scope: 'animal', checkKind: 'minLength', checkValue: '7' },
  },
  {
    id: 'double_letter_place',
    title: 'Double Trouble Place',
    description: 'The "Place" must contain the same letter twice in a row.',
    icon: 'Globe',
    ruleHint: 'A repeated letter pair in the Place.',
    rule: { scope: 'place', checkKind: 'doubleLetter', checkValue: '' },
  },
  {
    id: 'double_letter_name',
    title: 'Twice Over',
    description: 'The "Name" must contain the same letter twice in a row.',
    icon: 'Award',
    ruleHint: 'A repeated letter pair in the Name.',
    rule: { scope: 'name', checkKind: 'doubleLetter', checkValue: '' },
  },
  {
    id: 'vowel_ending_name',
    title: 'Names That Sing',
    description: 'The "Name" must end with a vowel (A, E, I, O or U).',
    icon: 'Award',
    ruleHint: 'Name must end in a vowel.',
    rule: { scope: 'name', checkKind: 'endsWithVowel', checkValue: '' },
  },
  {
    id: 'vowel_ending_animal',
    title: 'Creature Comfort',
    description: 'The "Animal" must end with a vowel (A, E, I, O or U).',
    icon: 'TreePine',
    ruleHint: 'Animal must end in a vowel.',
    rule: { scope: 'animal', checkKind: 'endsWithVowel', checkValue: '' },
  },
  {
    id: 'adjacent_vowels_thing',
    title: 'Twin Vowel Object',
    description: 'The "Thing" must contain two vowels next to each other, like "ea" or "oo".',
    icon: 'Layers',
    ruleHint: 'Two vowels touching in the Thing.',
    rule: { scope: 'thing', checkKind: 'adjacentVowels', checkValue: '' },
  },
  {
    id: 'ends_with_n',
    title: 'Ending On N',
    description: 'At least 2 answers must end with the letter N.',
    icon: 'Layers',
    ruleHint: 'Two answers ending in N.',
    rule: { scope: 'some', checkKind: 'endsWith', checkValue: 'n' },
  },
  {
    id: 'ends_with_e',
    title: 'Ending On E',
    description: 'At least 2 answers must end with the letter E.',
    icon: 'Layers',
    ruleHint: 'Two answers ending in E.',
    rule: { scope: 'some', checkKind: 'endsWith', checkValue: 'e' },
  },
  {
    id: 'ends_with_r_or_s',
    title: 'R Or S To Finish',
    description: 'At least 2 answers must end with the letter R or the letter S.',
    icon: 'Layers',
    ruleHint: 'Two answers ending in R or S.',
    rule: { scope: 'some', checkKind: 'endsWith', checkValue: 'r, s' },
  },
  {
    id: 'ends_with_ing',
    title: 'Thing With A Ring',
    description: 'The "Thing" must end in the letters ING, like "string".',
    icon: 'Sparkles',
    ruleHint: 'Thing must end in ING.',
    rule: { scope: 'thing', checkKind: 'endsWith', checkValue: 'ing' },
  },
  {
    id: 'mythology_theme',
    title: 'Myths And Legends',
    description: 'At least 2 answers must be connected to myths, legends or folklore.',
    icon: 'Award',
    ruleHint: 'Two answers linked to myth.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'sports_theme',
    title: 'Game On',
    description: 'At least 2 answers must be connected to sport or games.',
    icon: 'Layers',
    ruleHint: 'Two answers linked to sport.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'colour_theme',
    title: 'True Colours',
    description: 'At least 2 answers must be connected to a colour.',
    icon: 'Sparkles',
    ruleHint: 'Two answers linked to a colour.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'royal_theme',
    title: 'Crown Jewels',
    description: 'At least 2 answers must be connected to royalty or rulers.',
    icon: 'Award',
    ruleHint: 'Two answers linked to royalty.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'africa_theme',
    title: 'African Connection',
    description: 'At least 2 answers must have a connection to Africa.',
    icon: 'Flag',
    ruleHint: 'Two answers linked to Africa.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'story_theme',
    title: 'Page And Screen',
    description: 'At least 2 answers must be connected to a book, film or TV show.',
    icon: 'Award',
    ruleHint: 'Two answers linked to a story.',
    rule: { scope: 'some', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'tech_thing',
    title: 'Plugged In',
    description: 'The "Thing" must be electronic or a piece of technology.',
    icon: 'Layers',
    ruleHint: 'Thing must be electronic.',
    rule: { scope: 'thing', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'tool_thing',
    title: 'Right Tool For It',
    description: 'The "Thing" must be a tool you can hold in one hand.',
    icon: 'Layers',
    ruleHint: 'Thing must be a hand tool.',
    rule: { scope: 'thing', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'domestic_animal',
    title: 'Home And Farm',
    description: 'The "Animal" must be a pet or a farm animal.',
    icon: 'TreePine',
    ruleHint: 'Pet or farm animal.',
    rule: { scope: 'animal', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'water_animal',
    title: 'Life Aquatic',
    description: 'The "Animal" must be one that lives in water.',
    icon: 'Globe',
    ruleHint: 'Animal must live in water.',
    rule: { scope: 'animal', checkKind: 'none', checkValue: '' },
  },
  {
    id: 'city_place',
    title: 'City Limits',
    description: 'The "Place" must be a city or a town, not a country.',
    icon: 'Globe',
    ruleHint: 'Place must be a city or town.',
    rule: { scope: 'place', checkKind: 'none', checkValue: '' },
  },
];

export const DETERMINISTIC_CHALLENGE_COUNT = FROZEN_CHALLENGES.length;

export const BONUS_CHALLENGES: BonusChallenge[] = [...FROZEN_CHALLENGES, ...EXTRA_CHALLENGES];
