export const RULE_FAMILIES = [
  'a rule about word length, requiring every answer to reach a minimum number of letters',
  'a rule about word length that constrains only ONE named category, such as requiring a long Thing',
  'a rule requiring every answer to contain a minimum number of vowels',
  'a rule requiring two vowels side by side in every answer, such as "ea" or "oo"',
  'a rule requiring a double letter — the same letter twice in a row — in every answer',
  'a rule about how the words end, requiring every answer to end in a vowel',
  'a rule about how the words end, requiring one named category to end in a vowel',
  'a rule about a specific word ending, such as every answer ending in the same consonant (never the target letter)',

  'a rule about a shared theme of the sea, rivers or water',
  'a rule about a shared theme of weather, the sky or the seasons',
  'a rule about a shared theme of forests, plants or the wild',
  'a rule about a shared theme of food, drink or cooking',
  'a rule about a shared theme of travel, geography or famous landmarks',
  'a rule about a shared theme of space, stars or astronomy',
  'a rule about a shared theme of science, invention or technology',
  'a rule about a shared theme of history or the ancient world',
  'a rule about a shared theme of myth, legend or folklore',
  'a rule about a shared theme of music or dance',
  'a rule about a shared theme of art, books, film or television',
  'a rule about a shared theme of sport, games or competition',
  'a rule about a shared theme of colours',
  'a rule about a shared theme of kings, queens, leaders or power',
  'a rule about a shared theme of speed, flight or movement',
  'a rule about a shared theme of ice, cold or winter',
  'a rule about a shared theme of fire, heat or the desert',
  'a rule about a shared theme of money, trade or work',
  'a rule about a shared theme of school, learning or books',
  'a rule about a shared theme of India or South Asia',
  'a rule about a shared theme of things that are very large, or of things that are very small',
  'a rule about a shared theme of the human body or health',
  'a rule about a shared theme of danger, mystery or the frightening',

  'a rule constraining only the Name, requiring a famous or historical person',
  'a rule constraining only the Name, requiring a character from a book, film or myth',
  'a rule constraining only the Name, requiring a name commonly given to more than one gender or used worldwide',
  'a rule constraining only the Place, requiring a capital city',
  'a rule constraining only the Place, requiring a natural feature such as a river, mountain, lake or desert',
  'a rule constraining only the Place, requiring an island, an ocean or somewhere on the coast',
  'a rule constraining only the Place, requiring somewhere outside the country the player is likely in',
  'a rule constraining only the Animal, requiring one that can fly',
  'a rule constraining only the Animal, requiring one that lives in water',
  'a rule constraining only the Animal, requiring a bird, or requiring an insect',
  'a rule constraining only the Animal, requiring a wild predator rather than a pet or farm animal',
  'a rule constraining only the Thing, requiring something edible or drinkable',
  'a rule constraining only the Thing, requiring something found in a kitchen',
  'a rule constraining only the Thing, requiring something you can wear',
  'a rule constraining only the Thing, requiring something that carries people or moves',
  'a rule constraining only the Thing, requiring something found in a classroom or an office',
  'a rule constraining only the Thing, requiring something that makes a sound',
  'a rule constraining only the Thing, requiring something small enough to hold in one hand',
] as const;
