import { BonusChallenge } from '../../shared/contract';
import { DailyChallengeOrigin } from '../telemetry/types';
import { DailyChallengeStore, nullStore } from './store';

/** The seam for producing a bonus challenge. */
export interface BonusChallengeSource {
  next(letter: string): Promise<BonusChallenge>;
}

/** Tries the primary source and falls back on failure. */
export function withBonusFallback(
  primary: BonusChallengeSource,
  fallback: BonusChallengeSource
): BonusChallengeSource {
  return {
    async next(letter) {
      try {
        return await primary.next(letter);
      } catch (err) {
        console.error('Primary bonus source failed, falling back:', err);
        return fallback.next(letter);
      }
    },
  };
}

/**
 * Makes a source stable for a given day, across every replica.
 *
 * The daily puzzle's letter is derived deterministically from the date, but its
 * bonus challenge is generated by a model — so without coordination it changes
 * on every refresh and differs between players. Two layers stop that:
 *
 * - The **store** is the source of truth shared by all replicas. A replica that
 *   generates a challenge publishes it with putIfAbsent, so the first writer
 *   wins and everyone else adopts that value rather than overwriting it.
 * - The in-process **map** is a read-through cache, so the common path costs no
 *   network call. It caches the in-flight promise, which also collapses a
 *   first-request stampede within one replica.
 *
 * With the default nullStore this degrades to per-process caching, which is
 * correct for a single replica.
 */
export function cachedPerDate(
  sourceFor: (dateStr: string) => BonusChallengeSource,
  options: {
    store?: DailyChallengeStore;
    maxDays?: number;
    /**
     * Notified with how each request was satisfied. Kept as a callback so this
     * module stays ignorant of telemetry, and so the existing return type does
     * not change for callers that do not care.
     */
    onServed?: (origin: DailyChallengeOrigin, dateStr: string) => void;
  } = {}
) {
  const store = options.store ?? nullStore;
  const maxDays = options.maxDays ?? 7;
  const onServed = options.onServed ?? (() => {});
  const cache = new Map<string, Promise<BonusChallenge>>();

  async function resolve(dateStr: string, letter: string): Promise<BonusChallenge> {
    const stored = await store.get(dateStr);
    if (stored) {
      onServed('store', dateStr);
      return stored;
    }

    const generated = await sourceFor(dateStr).next(letter);

    // Another replica may have published one between the read and now; whichever
    // is stored wins, so every player sees the same challenge.
    const published = await store.putIfAbsent(dateStr, generated);

    // Losing that race means this replica adopted someone else's value, which
    // is a store hit, not a local generation. Reporting it as 'generated' would
    // show N generations for a date that was only generated once.
    onServed(published === generated ? 'generated' : 'store', dateStr);

    return published;
  }

  return {
    async forDate(dateStr: string, letter: string): Promise<BonusChallenge> {
      const cached = cache.get(dateStr);
      if (cached) {
        onServed('memory', dateStr);
        return cached;
      }

      const pending = resolve(dateStr, letter);
      cache.set(dateStr, pending);

      // A failure must not be cached, or the day is poisoned until restart.
      pending.catch(() => cache.delete(dateStr));

      // Keep the map from growing without bound across a long-lived process.
      if (cache.size > maxDays) {
        const oldest = [...cache.keys()].sort()[0];
        if (oldest) cache.delete(oldest);
      }

      return pending;
    },
  };
}
